#!/bin/sh
set -eu
exit_code=0
# shellcheck disable=SC2013
for conffile in $(awk '!/^#/ {print $4,$5,$6,$7}' ldm.conf); do
  skip="false"
  requested_timeout="$(grep "${conffile}" ldm.conf | awk '{print $3}')"
  multiplier="0"
  # shellcheck disable=SC2034
  for i in $(grep "${conffile}" ldm.conf | awk '{print $4,$5,$6,$7}'); do
    multiplier="$(( multiplier + 1 ))"
  done
  timeout="$(( requested_timeout * multiplier + 60 ))"
  if ! pgrep -f "unified_client .* ${requested_timeout}.*${conffile}" > /dev/null 2>&1; then
    printf "No unified_client running for configured %s\n" "${conffile}"
    exit_code=1
  fi
  ssid=$(sed -n -e 's/^[[:space:]]*//g' -e 's/"//g' -e '/ssid/s/ssid=//p' "config/${conffile}" | head -n1)
  if [ -f "/run/rfctf_status/${ssid}_attempt" ]; then
    attempt_mtime=$(stat -c %Y "/run/rfctf_status/${ssid}_attempt")
    currtime=$(date +%s)
    diff=$(( currtime - attempt_mtime ))
    if [ "${diff}" -gt "${timeout}" ]; then
      printf "No connection attempt on configured ssid %s in %ss\n" "${ssid}" "${diff}"
      exit_code=1
    fi
    unset attempt_mtime diff
    if [ "${ssid}" = 'RFHS_RFCTF_00' ] || [ "${ssid}" = 'RFHS_RFCTF_03' ] || [ "${ssid}" = 'RFHS_RFCTF_06' ]; then
      # These are client only, so no need to check if they successfully connected
      skip="true"
    fi
    if [ "${1:-}" != "--test" ] && [ "${skip}" = "false" ]; then
      if [ -f "/run/rfctf_status/${ssid}_active" ]; then
        active_mtime=$(stat -c %Y "/run/rfctf_status/${ssid}_active")
        currtime=$(date +%s)
        diff=$(( currtime - active_mtime ))
        if [ "${diff}" -gt "${timeout}" ]; then
          printf "No connection success on configured ssid %s in %ss\n" "${ssid}" "${diff}"
          exit_code=1
        fi
        unset active_mtime diff
      else
        printf "No connection success on configured ssid %s\n" "${ssid}"
        exit_code=1
      fi
    fi
  else
    printf "No connection attempt on configured ssid %s\n" "${ssid}"
    exit_code=1
  fi
done
exit "${exit_code}"
